### ISSUE TITLE
Language Switch

### ISSUE THREAD

**Issue by cedeber** [frontools/magnolia-megaton#15]
Java & FreeMarker configuration. It needs to detect the browser default language.

**Comment by Dalibor22x** [comment]
Problems:

- [ ] site config gets overwritten when the my-module gets re-installed.

**Comment by pierresandrin-oi** [comment]
Funktioniert nicht gut. Siehe Issue bei Nubo.
https://github.com/open-interactive/nubo/issues/3

**Comment by pierresandrin-oi** [comment]
Geht nicht wegen dem Cache. Das virtualUriMapping wird gar nicht aufgerufen wenn die Seite aus dem cache kommt. Das feature ist im Prinzip "personalized content". Ev ist eine Lösung per JS & cookie vorzuziehen.
